config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'register' => 'users#new'
  post 'register' => 'users#create'
  get 'user' => 'users#show'
  get 'user/edit' => 'users#edit', :as => 'user_edit'
  patch put 'user/update' => 'users#update', :as => 'user_update'

  post 'cart/add' => 'cart_items#create', :as => 'cart_items_add'
  post 'cart/refresh' => 'cart_items#refresh', :as => 'cart_items_refresh'
  post 'cart/update' => 'cart_items#update', :as => 'cart_items_update'
  delete 'cart/delete' => 'cart_items#destroy', :as => 'cart_items_delete'
  post 'cart/delete' => 'cart_items#destroy', :as => 'cart_items_delete_post'

  get 'cart' => 'carts#show'
  delete 'cart/clear' => 'carts#destroy', :as => 'cart_clear'

  resources :products

  # root :to => 'mall#index', :as => 'mall'
  root 'mall#index', as: 'mall'

  mount RuCaptcha::Engine => "/rucaptcha"

  get 'say/hello'
  get 'say/goodbye'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  # 一对多关联，销毁自身时删除所有关联项
  has_many :cart_items, :dependent => :destroy

  # 添加商品，累加数量
  def add_product(product)
    current_item = cart_items.find_by(product_id: product.id)
    if current_item
      current_item.count += 1
    else
      current_item = cart_items.build(product_id: product.id, count: 1)
    end
    current_item
  end

  def total_count
    cart_items.to_a.sum { |item| item.count }
  end

  def total_price
    cart_items.to_a.sum { |item| item.total_price }
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  skip_before_action :authorize, only: [:create, :update, :destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  # rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  # def index
  #   @carts = Cart.all
  # end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  # def new
  #   @cart = Cart.new
  # end

  # GET /carts/1/edit
  # def edit
  # end

  # POST /carts
  # POST /carts.json
  # def create
  #   @cart = Cart.new(cart_params)
  #
  #   respond_to do |format|
  #     if @cart.save
  #       format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
  #       format.json { render :show, status: :created, location: @cart }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @cart.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  # def update
  #   respond_to do |format|
  #     if @cart.update(cart_params)
  #       format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @cart }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @cart.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to mall_url, notice: '购物车已清空' }
      format.json { head :no_content }
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    # def invalid_cart
    #   logger.error "尝试访问无效购物车，ID为: #{params[:id]}"
    #   redirect_to mall_url, notice: '未找到购物车'
    # end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% unless cart && cart.cart_items.count > 0 %>
  <h3>购物车暂无商品，快去逛逛吧</h3>
<% else %>
  <style>
      .table-bordered td {
          padding: 0 !important;
          vertical-align: middle;
          text-align: center;
      }
      .btn-min {
          border: 1px solid #333 !important;
          background-color: #773c084d;
          border-radius: 6px;
      }
      .btn-min-clear {
          border: 1px solid #333 !important;
          border-radius: 6px;
      }
  </style>
  <table class="table table-bordered table-hover m-auto">
    <thead>
    <tr>
      <th>ID</th>
      <th>名称</th>
      <th>图片</th>
      <th>单价</th>
      <th>数量</th>
      <th>总价</th>
      <th>操作</th>
    </tr>
    </thead>

    <tbody>
    <%= render cart.cart_items %>

    <tr>
      <td colspan="2">总数量：<%= cart.total_count %></td>
      <td colspan="3">总金额：<%= number_to_currency cart.total_price, precision: 2, unit: '￥', strip_insignificant_zeros: true %></td>
      <td colspan="2"><%= button_to '清空购物车', cart_clear_path(cart_id: cart.id), method: :delete, data: {
          swal: {
              text: '您确定要清空吗？',
              type: 'question',
              confirm_button_class: 'btn btn-default',
              confirm_button_text: '是的',
              cancel_button_text: '算了',
          }}, class: 'btn-min-clear' %></td>
    </tr>
    </tbody>
  </table>
<% end %>

app/views/carts/_form.html.erb
<%#= form_with(model: cart, local: true) do |form| %>
  <%# if cart.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2><%#= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>-->

<!--      <ul>-->
      <%# cart.errors.full_messages.each do |message| %>
<!--        <li><%#= message %></li>-->
      <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

<!--  <div class="actions">-->
    <%#= form.submit %>
<!--  </div>-->
<%# end %>

app/views/carts/edit.html.erb
<!--<h1>Editing Cart</h1>-->

<%#= render 'form', cart: @cart %>

<!--<%#= link_to 'Show', @cart %> |-->
<%#= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>购物车总览</h1>

<table border="1px solid #ccc" style="text-align: center;">
  <thead>
    <tr>
      <th>购物车ID</th>
      <th>商品数量</th>
      <th>商品总价</th>
      <th colspan="3">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.id %></td>
        <td><%= cart.cart_items.count %></td>
        <td>

          <% cart_items_total = 0 %>
          <%#= cart.cart_items.map { |product| cart_items_total += product.price } %>
          <%#= cart_items_total %>
          <%#= eval cart.cart_items.each.product.price.join('+')%>
          <% cart.cart_items.each do |cart_item| %>
          <% cart_items_total += cart_item.product.price %>
          <% end %>
          <%= number_to_currency cart_items_total, precision: 2, unit: '￥', strip_insignificant_zeros: true %>
        </td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<!--<h1>New Cart</h1>-->

<%#= render 'form', cart: @cart %>

<%#= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="container">
  <% if notice %>
    <script type="application/javascript">
        $(function () {
            Swal.fire({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 3000,
                type: 'info',
                title: '<%= notice %>'
            })
        });
    </script>
  <% end %>

  <div class="row">
    <% unless @cart && @cart.cart_items.count > 0 %>
      <div class="col-md-10 offset-md-1 m-auto" style="text-align: center">
        <h1>购物车</h1>
        <h5>购物车暂无商品，快去 <%= link_to '逛逛', mall_url %> 吧</h5>
      </div>
    <% else %>
      <div class="col-md-10 offset-md-1 m-auto" style="text-align: center">
        <h1>购物车</h1>
        <style>
          .table-bordered td {
              vertical-align: middle;
          }
        </style>
        <table class="table table-bordered table-striped" style="vertical-align: middle !important;">
          <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名称</th>
            <th>商品图片</th>
            <th>商品单价</th>
            <th>商品数量</th>
            <th>商品总价</th>
            <th>操作</th>
          </tr>
          </thead>

          <tbody>

          <%= render @cart.cart_items %>

            <tr>
              <td colspan="3">总数量：<%= @cart.total_count %></td>
              <td colspan="3">总金额：<%= number_to_currency @cart.total_price, precision: 2, unit: '￥', strip_insignificant_zeros: true %></td>
              <td colspan="1"><%= button_to '清空购物车', cart_clear_path(cart_id: @cart.id), method: :delete, data: {
                  swal: {
                      text: '您确定要清空吗？',
                      type: 'question',
                      confirm_button_class: 'btn btn-default',
                      confirm_button_text: '是的',
                      cancel_button_text: '算了',
                  }}, class: 'btn btn-clear', id: 'clear-cart' %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <script type="application/javascript">
          $(function () {
              ajaxBind('#clear-cart');
          })
      </script>
      <div class="col-md-2 offset-md-1">
        <%= link_to '返回首页', mall_url %>
      </div>
    <% end %>
  </div>
</div>