config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'register' => 'users#new'
  post 'register' => 'users#create'
  get 'user' => 'users#show'
  get 'user/edit' => 'users#edit', :as => 'user_edit'
  patch put 'user/update' => 'users#update', :as => 'user_update'

  post 'cart/add' => 'cart_items#create', :as => 'cart_items_add'
  post 'cart/refresh' => 'cart_items#refresh', :as => 'cart_items_refresh'
  post 'cart/update' => 'cart_items#update', :as => 'cart_items_update'
  delete 'cart/delete' => 'cart_items#destroy', :as => 'cart_items_delete'
  post 'cart/delete' => 'cart_items#destroy', :as => 'cart_items_delete_post'

  get 'cart' => 'carts#show'
  delete 'cart/clear' => 'carts#destroy', :as => 'cart_clear'

  resources :products

  # root :to => 'mall#index', :as => 'mall'
  root 'mall#index', as: 'mall'

  mount RuCaptcha::Engine => "/rucaptcha"

  get 'say/hello'
  get 'say/goodbye'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  # 外键关联，计数器缓存字段 count
  belongs_to :product, counter_cache: :count
  belongs_to :cart

  def total_price
    product.price * count
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  # before_action :set_cart_item, only: [:show, :edit, :update, :destroy]
  include CurrentCart
  before_action :set_cart, only: [:update, :create, :refresh, :destroy]
  before_action :set_cart_item, only: [:update, :destroy]

  # GET /cart_items
  # GET /cart_items.json
  # def index
  #   @cart_items = CartItem.all
  #   # @cart_items = CartItem.find_by_cart_id(params[:cart_id]) unless nil || []
  # end

  # GET /cart_items/1
  # GET /cart_items/1.json
  # def show
  # end

  # GET /cart_items/new
  # def new
  #   @cart_item = CartItem.new
  # end

  # GET /cart_items/1/edit
  # def edit
  # end

  # 渲染首页购物车
  # POST /cart_items/1
  # POST /cart_items/1.json
  def refresh
    respond_to do |format|
      format.js
    end
  end

  # 添加商品到购物车
  # POST /cart_items
  # POST /cart_items.json
  def create
    product = Product.find(params[:product_id])
    @cart_item = @cart.add_product(product)

    respond_to do |format|
      if @cart_item.save
        format.json { render_ajax_success msg: '成功添加到购物车'}
        # format.html { redirect_to cart_url, notice: '成功添加到购物车' }
        # format.js
        # format.json { render :show, status: :created, location: @cart_item }
      else
        format.json { render_ajax_failure msg: '添加到购物车失败' }
        # format.html { render :new, notice: '添加到购物车失败' }
        # format.js
        # format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # 修改购物车商品信息（数量）
  # PATCH/PUT /cart_items/1
  # PATCH/PUT /cart_items/1.json
  def update
    respond_to do |format|
      if @cart_item.update(cart_params)
        format.html { redirect_to cart_url, notice: '购物车商品已修改' }
        format.json { render :show, status: :ok, location: @cart_item }
      else
        format.html { render :edit }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # 删除购物车内的商品
  # DELETE /cart_items/1
  # DELETE /cart_items/1.json
  def destroy
    @cart_item.destroy
    respond_to do |format|
      if params[:_method] != 'delete'
        format.js
        format.json { render_ajax_success msg: '购物车商品已删除' }
        # format.json { head :no_content }
      else
        format.html { redirect_to cart_url, notice: '购物车商品已删除' }
        # format.js
        format.json { head :no_content }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cart_item
    # @cart_item = CartItem.find_by(:cart_id => session[:cart_id], :product_id => params[:product_id])
    @cart_item = @cart.cart_items.find_by(:product_id => params[:product_id])
  end

  # Only allow a list of trusted parameters through.
  def cart_item_params
    params.require(:cart_item).permit(:product_id, :count || 1)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_cart_item.html.erb
  <tr>
    <td><%= cart_item.id %></td>
    <td><%= cart_item.product.title %></td>
    <td><%= image_tag cart_item.product.image_url, :size => '120x80' %></td>
    <td><%= cart_item.product.price %></td>
    <td><%= cart_item.count %></td>
    <td>

      <%#= cart.cart_items.map { |product| cart_items_total += product.price } %>
      <%#= cart_items_total %>
      <%#= eval cart.cart_items.each.product.price.join('+')%>

      <%# cart.cart_items.each do |cart_item| %>
      <%# cart_items_total += cart_item.product.price %>
      <%# end %>
      <%= number_to_currency cart_item.total_price, precision: 2, unit: '￥', strip_insignificant_zeros: true %>
    </td>
    <!--      <td><%#= link_to 'Show', cart %></td>-->
    <!--      <td><%#= link_to 'Edit', edit_cart_path(cart) %></td>-->
    <td>
      <% if @is_ajax %>
        <%= button_to '删除', cart_items_delete_post_path(product_id: cart_item.product.id), method: :post, remote: true, class: 'btn-min' %>
      <% else %>
        <%= button_to '删除', cart_items_delete_path(product_id: cart_item.product.id), method: :delete, remote: @is_ajax || false %>
      <% end %>
    </td>
  </tr>

app/views/cart_items/_form.html.erb
<%= form_with(model: cart_item, local: true) do |form| %>
  <% if cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% cart_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.number_field :cart_id %>
  </div>

  <div class="field">
    <%= form.label :count %>
    <%= form.number_field :count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cart_items/edit.html.erb
<!--<h1>Editing Cart Item</h1>-->

<%#= render 'form', cart_item: @cart_item %>

<!--<%#= link_to 'Show', @cart_item %> |-->
<%#= link_to 'Back', cart_items_path %>

app/views/cart_items/index.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<!--<h1>Cart Items</h1>-->

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Product</th>-->
<!--      <th>Cart</th>-->
<!--      <th>Count</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
    <%# @cart_items.each do |cart_item| %>
<!--      <tr>-->
<!--        <td><%#= cart_item.product_id %></td>-->
<!--        <td><%#= cart_item.cart_id %></td>-->
<!--        <td><%#= cart_item.count %></td>-->
<!--        <td><%#= link_to 'Show', cart_item %></td>-->
<!--        <td><%#= link_to 'Edit', edit_cart_item_path(cart_item) %></td>-->
<!--        <td><%#= link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
    <%# end %>
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

<%#= link_to 'New Cart Item', new_cart_item_path %>

app/views/cart_items/new.html.erb
<!--<h1>New Cart Item</h1>-->

<%#= render 'form', cart_item: @cart_item %>

<%#= link_to 'Back', cart_items_path %>

app/views/cart_items/refresh.js.erb
$('#cart').html("<%= j render(@cart) %>");

app/views/cart_items/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<!--<p>-->
<!--  <strong>Product:</strong>-->
  <%#= @cart_item.product_id %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Cart:</strong>-->
  <%#= @cart_item.cart_id %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Count:</strong>-->
  <%#= @cart_item.count %>
<!--</p>-->

<!--<%#= link_to 'Edit', edit_cart_item_path(@cart_item) %> |-->
<%#= link_to 'Back', cart_items_path %>